ifneq (,$(filter registry_cli%,$(USEMODULE)))
  USEMODULE += registry_path
endif

ifneq (,$(filter registry_storage%,$(USEMODULE)))
  include $(RIOTBASE)/sys/registry/storage/Makefile.dep
endif

ifneq (,$(filter registry_sys_namespace%,$(USEMODULE)))
  include $(RIOTBASE)/sys/registry/sys_namespace/Makefile.dep
endif

ifneq (,$(filter registry_%,$(USEMODULE)))
  USEMODULE += registry
endif
