ifneq (,$(filter registry_cli%,$(USEMODULE)))
  USEMODULE += registry_path
endif

ifneq (,$(filter registry_storage%,$(USEMODULE)))
  include $(RIOTBASE)/sys/registry/storage/Makefile.dep
endif

ifneq (,$(filter registry_namespace_sys%,$(USEMODULE)))
  include $(RIOTBASE)/sys/registry/namespace_sys/Makefile.dep
endif

ifneq (,$(filter registry_%,$(USEMODULE)))
  USEMODULE += registry
endif

USEMODULE += fmt
USEMODULE += base64