USEMODULE += littlefs2
USEMODULE += mtd
USEMODULE += vfs

USEMODULE +=  registry_namespace_tests_full
USEMODULE +=  registry_namespace_tests_constrained_min_max
USEMODULE +=  registry_namespace_tests_constrained_allowed_values
USEMODULE +=  registry_namespace_tests_constrained_forbidden_values
# USEMODULE += registry_storage_vfs