include ../Makefile.tests_common

# required modules
USEMODULE += littlefs2
USEMODULE += mtd
USEMODULE += vfs

USEMODULE += registry_schema_rgb_led
USEMODULE += registry_storage_vfs

include $(RIOTBASE)/Makefile.include
