include ../Makefile.tests_common

# required modules
USEMODULE += littlefs2
USEMODULE += mtd
USEMODULE += vfs

USEMODULE += registry
USEMODULE += registry_schemas
USEMODULE += registry_storage_facility_vfs

include $(RIOTBASE)/Makefile.include
