name: Build Docs

on:
    push:
        branches:
            - master
        paths:
            - 'doc/guides/**'
            - 'doc/starlight/**'
            - 'CODE_OF_CONDUCT.md'
            - 'GOVERNANCE.md'
            - 'CONTRIBUTING.md'
            - 'CODING_CONVENTIONS*.md'
            - 'release-notes.txt'

jobs:
    build-docs:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: doc/starlight
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4
          - name: Set up Node.js
            uses: actions/setup-node@v4
          - name: Build documentation
            run: make build
            # This step will probably need to be changed to use the actual service RIOT is using
            # This makes it more convenient to deploy while still in development though
          - name: Deploy documentation
            uses: peaceiris/actions-gh-pages@v3
            with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: doc/starlight/dist
                publish_branch: gh-pages
                cname: guide.riot-os.org
                commit_message: "Deploy documentation"
