name: Guide Docs Build Test

on:
    pull_request:
        paths:
            - 'doc/guides/**'
            - 'doc/starlight/**'
            - 'CODE_OF_CONDUCT.md'
            - 'GOVERNANCE.md'
            - 'CONTRIBUTING.md'
            - 'CODING_CONVENTIONS*.md'
            - 'release-notes.txt'

jobs:
    build-docs:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: doc/starlight
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4
          - name: Set up Node.js
            uses: actions/setup-node@v4
          - name: Build documentation
            run: make build
